version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "es1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a8v7z5huq5yg"
s3_prefix = "es1"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
